### ISSUE TITLE
How can I run this service?

### ISSUE THREAD

**Issue by RafaJimenezR98** [Bluetab/td-df#1]
Hello, I am trying to run Truedat Dynamic Forms service, but I am getting this error:

`** (Mix) Could not start application td_df: {:not_running, :td_cache}`

I have downloaded td_cache too but I can't run this service.

Any help will be grateful, thanks.

**Comment by RafaJimenezR98** [comment]
Thanks a lot, my problem was that Redis wasn't started. I configured it and all run OK.
Another issue I have is when i run td-df application (I run it in ubuntu server), when I go to the browser (192.168....:4013) it show me this error:
`Phoenix.Router.NoRouteError at GET /
no route found for GET / (TdDfWeb.Router)`

I Think it's because I need to access to a different URL like: http://192.168...:4013/api/swagger

Thanks!

**Comment by tcrossland** [comment]
@RafaJimenezR98 this service is a REST API, it doesn't include a web front-end. You can see which routes it publishes by using `mix phx.routes` or by looking at the `router.ex` file.

**Comment by RafaJimenezR98** [comment]
@tcrossland thanks a lot, you can close this issue at anytime.

**Comment by tcrossland** [comment]
Happy to help.
